# Every file shall have a comment
# Runs:
#		$ lex lab1.l
#   $ gcc lex.yy.c -o lab1
# lab1.l -> lex.yy.c -> lab1
# Devon Sookhoo
# August 20, 2025

all: 	lab1

lab1:	lab1.l
			lex lab1.l
			gcc lex.yy.c -o lab1

clean:
			rm -f lab1
